# Load data

In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')
df

,No,Kategori,Nama_Tempat,Alamat,Latitude,Longitude,No_Telp,Harga,Jumlah_Kamar,Jumlah_bed,...,OYO,Reddoorz,Traveloka_link,Tiket_link,Booking_link,Agoda_link,Trip_link,OYO_link,Reddoorz_link,Bintang
0,1,Hotel,KUSUMA AGRO WISATA HOTEL,"Jl. Abdul Gani Atas, Ngaglik, Kec. Batu, Kota ...",-7.882860,112.5147166,"(0341) 593333, 08001593333",338.754 - 1.365.936,153,355,...,0,0,NaN,https://www.tiket.com/hotel/indonesia/kusuma-a...,https://www.booking.com/searchresults.id.html?...,https://www.agoda.com/search?searchdatetype=de...,NaN,NaN,NaN,4
1,2,Hotel,AMARTAHILLS HOTEL AND RESORT \n,"Jl. Abdul Gani Atas, Ngaglik, Kec. Batu, Kota ...",-7.888800,112.5141399,(0341) 525777,584.027- 4.602.695,162,246,...,0,0,https://www.traveloka.com/id-id/hotel/indonesi...,https://www.tiket.com/hotel/indonesia/amartahi...,https://www.booking.com/hotel/id/horison-ultim...,NaN,NaN,NaN,NaN,4
2,3,Hotel,ZAM-ZAM HOTEL,"Jl. Abdul Gani Atas, RT.04/RW.10, Ngaglik, Kec...",-7.882542,112.517915,(0341) 591148,386.534 - 600.040,85,115,...,0,0,https://www.traveloka.com/id-id/hotel/indonesi...,https://www.tiket.com/hotel/indonesia/zamzam-h...,NaN,NaN,NaN,NaN,NaN,4
3,4,Hotel,ASTON INN BATU\n,"Jl. Abdul Gani Atas No.42-44, Ngaglik, Kec. Ba...",-7.882252,112.5201178,0812-3453-8908,797.150 - 1.668.232,99,196,...,0,0,https://www.traveloka.com/id-id/hotel/detail?s...,https://www.tiket.com/hotel/indonesia/aston-in...,https://www.booking.com/searchresults.id.html?...,https://www.agoda.com/id-id/search?campaignid=...,NaN,NaN,NaN,4
4,5,Hotel,CIPTANINGATI HOTEL,"Jl. Argopuro No.154, Sisir, Kec. Batu, Kota Ba...",-7.875583,112.5338801,(0341) 3061474,277.114- 650.000,60,90,...,0,0,https://www.traveloka.com/id-id/hotel/indonesi...,https://www.tiket.com/hotel/indonesia/ciptanin...,NaN,https://www.agoda.com/id-id/ciptaningati-hotel...,NaN,NaN,NaN,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
529,531,Villa,VILLA rAFASA,"Jl. Indragiri, Sumberejo, Kec. Batu, Kota Batu...",-7.853382,112.5153996,"081330209093, 082332754317",NaN,8,8,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
530,532,Villa,VillaTiga Putri,"Jl. Mawar No.97, Songgokerto, Kota Batu",-7.867076,112.5048256,NaN,NaN,10,20,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
531,533,Villa,Villa Aqhuillah,"Jl. Arumdalu Jl. Perum Bukit Songgoriti No.37,...",-7.861673,112.4994658,NaN,NaN,3,3,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
532,534,Villa,Villa Variz 2,"jl. Durian, Songgokerto, Kec. Batu, Kota Batu,...",-7.864424,112.4950485,85231190506,NaN,3,3,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
533,535,Villa,Villa Puspa Sari 1,"Songgokerto, Batu, kota batu, jawa timur 65312",-7.863267,112.4989641,8563122887,NaN,3,3,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Checker

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

No                  0
Kategori            0
Nama_Tempat         0
Alamat              0
Latitude            0
Longitude           0
No_Telp            26
Harga             346
Jumlah_Kamar        0
Jumlah_bed          0
Fasilitas         160
Keunggulan        457
Instagram         362
Website           466
Traveloka           0
Tiket               0
Booking             0
Agoda               0
Trip                0
OYO                 0
Reddoorz            0
Traveloka_link    347
Tiket_link        329
Booking_link      468
Agoda_link        399
Trip_link         504
OYO_link          523
Reddoorz_link     519
Bintang           464
dtype: int64

In [ ]:
import numpy as np
df = df.replace('', np.nan)

In [ ]:
df

,No,Kategori,Nama_Tempat,Alamat,Latitude,Longitude,No_Telp,Harga,Jumlah_Kamar,Jumlah_bed,...,OYO,Reddoorz,Traveloka_link,Tiket_link,Booking_link,Agoda_link,Trip_link,OYO_link,Reddoorz_link,Bintang
0,1,Hotel,KUSUMA AGRO WISATA HOTEL,"Jl. Abdul Gani Atas, Ngaglik, Kec. Batu, Kota ...",-7.882860,112.5147166,"(0341) 593333, 08001593333",338.754 - 1.365.936,153,355,...,0,0,NaN,https://www.tiket.com/hotel/indonesia/kusuma-a...,https://www.booking.com/searchresults.id.html?...,https://www.agoda.com/search?searchdatetype=de...,NaN,NaN,NaN,4
1,2,Hotel,AMARTAHILLS HOTEL AND RESORT \n,"Jl. Abdul Gani Atas, Ngaglik, Kec. Batu, Kota ...",-7.888800,112.5141399,(0341) 525777,584.027- 4.602.695,162,246,...,0,0,https://www.traveloka.com/id-id/hotel/indonesi...,https://www.tiket.com/hotel/indonesia/amartahi...,https://www.booking.com/hotel/id/horison-ultim...,NaN,NaN,NaN,NaN,4
2,3,Hotel,ZAM-ZAM HOTEL,"Jl. Abdul Gani Atas, RT.04/RW.10, Ngaglik, Kec...",-7.882542,112.517915,(0341) 591148,386.534 - 600.040,85,115,...,0,0,https://www.traveloka.com/id-id/hotel/indonesi...,https://www.tiket.com/hotel/indonesia/zamzam-h...,NaN,NaN,NaN,NaN,NaN,4
3,4,Hotel,ASTON INN BATU\n,"Jl. Abdul Gani Atas No.42-44, Ngaglik, Kec. Ba...",-7.882252,112.5201178,0812-3453-8908,797.150 - 1.668.232,99,196,...,0,0,https://www.traveloka.com/id-id/hotel/detail?s...,https://www.tiket.com/hotel/indonesia/aston-in...,https://www.booking.com/searchresults.id.html?...,https://www.agoda.com/id-id/search?campaignid=...,NaN,NaN,NaN,4
4,5,Hotel,CIPTANINGATI HOTEL,"Jl. Argopuro No.154, Sisir, Kec. Batu, Kota Ba...",-7.875583,112.5338801,(0341) 3061474,277.114- 650.000,60,90,...,0,0,https://www.traveloka.com/id-id/hotel/indonesi...,https://www.tiket.com/hotel/indonesia/ciptanin...,NaN,https://www.agoda.com/id-id/ciptaningati-hotel...,NaN,NaN,NaN,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
529,531,Villa,VILLA rAFASA,"Jl. Indragiri, Sumberejo, Kec. Batu, Kota Batu...",-7.853382,112.5153996,"081330209093, 082332754317",NaN,8,8,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
530,532,Villa,VillaTiga Putri,"Jl. Mawar No.97, Songgokerto, Kota Batu",-7.867076,112.5048256,NaN,NaN,10,20,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
531,533,Villa,Villa Aqhuillah,"Jl. Arumdalu Jl. Perum Bukit Songgoriti No.37,...",-7.861673,112.4994658,NaN,NaN,3,3,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
532,534,Villa,Villa Variz 2,"jl. Durian, Songgokerto, Kec. Batu, Kota Batu,...",-7.864424,112.4950485,85231190506,NaN,3,3,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
533,535,Villa,Villa Puspa Sari 1,"Songgokerto, Batu, kota batu, jawa timur 65312",-7.863267,112.4989641,8563122887,NaN,3,3,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Cleaning

lowercase

In [ ]:
cols = ["Kategori", "Nama_Tempat", "Alamat", "Fasilitas", "Keunggulan"]

for col in cols:
    df[col] = df[col].astype(str).str.lower()

menghapus spasi dan newline di awal/akhir pada 3 kolom

In [ ]:
cols = ['Nama_Tempat', 'Fasilitas', 'Keunggulan']

for col in cols:
    df[col] = df[col].astype(str).str.strip()  # hapus spasi dan newline di awal/akhir

membersihan dan membuat konsistensi pada kolom no. telp

In [ ]:
import re
import pandas as pd
import numpy as np

def clean_phone_numbers(phone):
    if pd.isna(phone):
        return phone  # biarkan NaN tetap NaN

    # Pisahkan nomor kalau ada koma
    numbers = [n.strip() for n in phone.split(',')]

    cleaned_numbers = []
    for num in numbers:
        # Hapus semua karakter non-digit
        num = re.sub(r'\D', '', num)

        # Kalau diawali '62', ganti jadi '0'
        if num.startswith('62'):
            num = '0' + num[2:]

        # Kalau belum diawali '0' dan tidak kosong, tambahkan '0'
        if num != '' and not num.startswith('0'):
            num = '0' + num

        cleaned_numbers.append(num)

    # Gabungkan kembali pakai koma
    return ', '.join(cleaned_numbers)


df['No_Telp'] = df['No_Telp'].apply(clean_phone_numbers)

mengubah singkatan jl

In [ ]:
import pandas as pd
import re

def clean_jalan(text):
    if pd.isna(text):
        return text
    # Ganti jl/jl. jadi jalan
    text = re.sub(r'\bjln?\.?\b', 'jalan', text)
    # Hapus titik setelah kata jalan
    text = re.sub(r'jalan\.', 'jalan', text)
    # Hapus spasi ganda kalau ada
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['Alamat'] = df['Alamat'].apply(clean_jalan)

menghapus karakter selain angka (1500000\u2063)

In [ ]:
import pandas as pd
import re

# Fungsi untuk hapus semua karakter non-digit
def clean_non_digit(text):
    if pd.isna(text):
        return text
    return re.sub(r'[^\d\-\s]', '', text)  # hanya simpan angka, spasi, dan strip

# Terapkan ke kolom harga
df['Harga'] = df['Harga'].apply(clean_non_digit)

memisahkan kolom harga menjadi 2 kolom dan membetulkan format

In [ ]:
import pandas as pd
import re

def split_harga_safe(x):
    if pd.isna(x) or str(x).strip() == '':
        return pd.Series([pd.NA, pd.NA])

    # Bersihkan karakter non-digit kecuali strip
    x = re.sub(r'[^\d\-\s]', '', str(x))

    # Split berdasarkan strip
    parts = x.split('-')

    min_harga = parts[0].strip()
    max_harga = parts[1].strip() if len(parts) > 1 else ''

    # Convert ke int, kalau kosong tetap pd.NA
    min_harga = int(min_harga) if min_harga != '' else pd.NA
    max_harga = int(max_harga) if max_harga != '' else pd.NA

    # Normalisasi harga kurang dari 1000 → kali 1000
    if min_harga is not pd.NA and min_harga < 1000:
        min_harga *= 1000
    if max_harga is not pd.NA and max_harga < 1000:
        max_harga *= 1000

    return pd.Series([min_harga, max_harga])

# Terapkan ke DataFrame, pakai Int64 untuk mendukung missing value
df[['Harga_min', 'Harga_max']] = df['Harga'].apply(split_harga_safe).astype('Int64')

hapus kolom harga dan memindahkan kolom harga min dan max kedepan

In [ ]:
import pandas as pd

# Hapus kolom harga
df = df.drop(columns=['Harga'])

# Tentukan urutan kolom baru
cols = list(df.columns)
# Ambil index kolom No_telp
idx = cols.index('No_Telp')
# Susun ulang kolom: semua kolom sampai No_telp + harga_min/harga_max + sisa kolom
new_cols = cols[:idx+1] + ['Harga_min', 'Harga_max'] + [c for c in cols[idx+1:] if c not in ['Harga_min','Harga_max']]

df = df[new_cols]

membuat point untuk kolom keunggulan

In [ ]:
import pandas as pd

def ubah_jadi_point(teks):
    # Biarkan null tetap null
    if pd.isna(teks) or str(teks).strip() == '':
        return pd.NA

    # Kalau sudah ada strip di awal teks, kembalikan apa adanya
    if str(teks).strip().startswith('-'):
        return teks

    # Ganti newline dengan spasi
    teks = teks.replace('\n', ' ')

    # Pisah berdasarkan titik
    bagian = teks.split('.')

    # Hapus spasi awal/akhir dan bagian kosong
    bagian = [b.strip() for b in bagian if b.strip()]

    # Tambahkan tanda '-'
    return '\n'.join(['- ' + b for b in bagian])

df['Keunggulan'] = df['Keunggulan'].apply(ubah_jadi_point)

membuat kolom baru untuk mengetahui tersedia di platform mana

In [ ]:
import pandas as pd

# Kolom-kolom platform
platform_cols = ['Traveloka', 'Tiket', 'Booking', 'Agoda', 'Trip', 'OYO', 'Reddoorz']

# Buat kolom baru, kosong jadi NaN
def gabung_platform(row):
    hasil = ', '.join([col for col in platform_cols if row[col] == 1])
    return hasil if hasil else np.nan  # kosong jadi NaN

df['Platform_tersedia'] = df[platform_cols].apply(gabung_platform, axis=1)

# save data

In [ ]:
df.to_csv('data_cleaned.csv', index=False)

In [ ]:
import csv
df.to_csv('data_clean.csv', index=False, quoting=csv.QUOTE_ALL)

In [ ]:
df.to_excel('data_clean.xlsx', index=False)